repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.5.1
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/python-poetry/poetry
    rev: "2.1.3"
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: []
        additional_dependencies: ["platformdirs>=4.3.6,<5", "rgmining-fraud-eagle>=0.10.5", "rgmining-fraudar>=0.7.5", "rgmining-rsd>=0.3.5", "click>=8", "pytest>=8.3.5", "types-requests>=2.32.0.20250306", "types-tqdm>=4.67.0.20250319"]
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
